### ISSUE TITLE
nfc-mflock or nfc-mklock ?

### ISSUE THREAD

**Issue by YangtseSu** [duament/nfc-mflock#1]
nfc-mflock or nfc-mklock

**Comment by duament** [comment]
`mf` means Mifare. It's derived from https://github.com/nfc-tools/libnfc/blob/master/examples/nfc-mfsetuid.c.

**Comment by YangtseSu** [comment]
But the binary is mklock. Is it a typo ?
 Usage: nfc-mklock [OPTIONS] [LOCK COMMAND]
二进制文件是nfc-mklock。项目名称是nfc-mflock。这是打错字了吗？

**Comment by duament** [comment]
Fixed.
